name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - dev
      - staging
      - main


jobs:
  # build_npm:
  #   name: Build Node Packages
  #   runs-on: arc-runner-set
  #   permissions:
  #     contents: write
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Setup Node
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: '21.7.3'

  #     - name: Cache node modules
  #       id: cache-npm
  #       uses: actions/cache@v4.2.2
  #       with:
  #         path: |
  #           node_modules
  #           ~/.npm
  #         key: dojo-chain-api-node-modules-${{ hashFiles('**/package-lock.json') }}
  #         restore-keys: |
  #           dojo-chain-api-node-modules-

  #     - name: NPM Install
  #       run: npm install --force

  #     - name: Run Build
  #       run: npm run build

  #     - name: List DIR
  #       run: ls -alth

  build_kami_image:
    name: Build Kami Image
    uses: ./.github/workflows/docker_build.yaml
    permissions:
        contents: read
        packages: write
    # needs:
    #   - build_npm

  build_docs_image:
    name: Build Kami Docs Image
    uses: ./.github/workflows/docs_build.yaml
    permissions:
        contents: read
        packages: write
    # needs:
    #   - build_npm
    
