on:
  release:
    types:
      - published
  workflow_call:

jobs:
  docker_publish:
    name: Docker Build
    runs-on: arc-runner-set
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # - name: Setup Node
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: '21.7.3'

      # - name: Cache node modules
      #   uses: actions/cache@v4.2.2
      #   with:
      #     path: |
      #       node_modules
      #       ~/.npm
      #     key: dojo-chain-api-node-modules
      #     restore-keys: |
      #       dojo-chain-api-node-modules

      - name: Login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
            type=ref,event=branch,enable=${{ github.ref != 'refs/heads/main' }}
            type=ref,event=tag

      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
